### ISSUE TITLE
Ingress paths - Can't run Grafana and Blockscout in parallel

### ISSUE THREAD

**Issue by YounesBM** [ConsenSys/quorum-kubernetes#112]
Hi @joshuafernandes,

I have a problem running Grafana and Blockscout in parallel.

It seems that both are configured to run on the "/" path. No matter how much I change the ingress, I can't get both to run at the same time.

Can you please help me fix this?

Thanks!

Cheers
Younes

**Comment by joshuafernandes** [comment]
Hi @YounesBM 

You'll have to set a base url/path or equivalent for one of the two and some nginx rules - similar to what I've done for kibana here https://github.com/ConsenSys/quorum-kubernetes/blob/master/ingress/ingress-rules-besu.yml#L12 and set the base prefix  https://github.com/ConsenSys/quorum-kubernetes/blob/master/ingress/ingress-rules-besu.yml#L35 

Its essentially a reverse proxy with the nginx you need to configure https://grafana.com/tutorials/run-grafana-behind-a-proxy/. If you get this working before I have a chance to look at, feel free to submit a PR across and we can merge

Cheers
Josh

**Comment by YounesBM** [comment]
Hi @joshuafernandes,

I was able to get Grafana and Blockscout working, but I had to modify the Grafana docker image first.

In the conf/defaults.ini file, I had to modify the following lines:


```
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
```

Then, for the ingress on Besu side, I modified the following lines:


```
nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/grafana/(.*)  /$1 break;
```

```
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: quorum-monitoring-monitoring-grafana
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blockscout
                port:
                  number: 4000
```

Cheers,
Younes
