### ISSUE TITLE
The local persistent volume is re-used when we re-create quorum blockchain.

### ISSUE THREAD

**Issue by scalalang2** [ConsenSys/quorum-kubernetes#116]
Hi. 
I've tested `dev` helm charts over time.
And I found that if I configure the blockchain more than once, 
the persistent volume of the second configured nodes seems to be reused.

I built go-quorum blockchain in `quorum` namespace 3 days ago. It seems fine.
But, after 3 days. I deleted all resources in `quorum` namespace. 
And I configured it `testnet` namespace again.

In second time, the block height of node is not starting from 1, it is 65536.

```
> eth.getBlock(1)
{
  ...
  timestamp: 1646281365, // Thu Mar 03 2022 04:22:45 GMT+0000, but current timestamp is Mar 08 2022
  ...
}
```

I think the reason is that the storage class of PV is not valid when the provider is local.
```yaml
# provider: local
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "goquorum-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: {{ include "goquorum-node.fullname" . }}-storage # it is not valid storage class right?
  capacity:
    storage: "{{ .Values.storage.sizeLimit }}"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/{{ include "goquorum-node.fullname" . }}"
```
