### ISSUE TITLE
Blocksckout return a 503 error on the browser

### ISSUE THREAD

**Issue by 0x3N3JVhPUV** [ConsenSys/quorum-kubernetes#155]
Hello,

I successfully deployed Blockscout. However, I get a 503 error on the browser, while Its pod is running on Kubernetes. 

Here is the error:
 
![image](https://user-images.githubusercontent.com/46408093/173207647-72fef7de-d4ac-4ff8-a7ba-8f00072ce483.png)

Here are the logs :

![image](https://user-images.githubusercontent.com/46408093/173207711-aa6f27ae-5418-4bb1-bc41-61b679a8fbf1.png)

Any idea of why this happens?

Regards

**Comment by Ezzahhh** [comment]
Hello,

When you deploy Blockscout you will need to specify which node it will use to pull information from the network. You will need to specify the service name on line 33 of helm/values/blockscout-besu.yml. Your logs suggest that it is trying to look for besu-node-member-1 and getting a 404 so it likely does not exist.

**Comment by andyafene** [comment]
Thank you your prompt answer @Ezzahhh,

It's strange because I already specified the service name "besu-node-member-1" on line 32 of helm/values/blockscout-besu.yml.
I still get the following logs:
![image](https://user-images.githubusercontent.com/46408093/173210718-84373084-91c1-4419-83a9-f1bbc891e475.png)

Here is my helm/values/blockscout-besu.yml:
![image](https://user-images.githubusercontent.com/46408093/173210648-b3bb95c3-7a9a-4c6e-bc7c-fce002ec984e.png)

I need help please,

Regards

**Comment by anuj-upadhyay-inferenz** [comment]
@0x3N3JVhPUV Do you have a `besu-node-member-1` pod running in your cluster?

You can check it by running `kubectl get pods -n quorum` and looking at it's output for `besu-node-member-1`

if it isn't installed you'll need to follow [these](https://github.com/ConsenSys/quorum-kubernetes/tree/master/helm#for-besu) steps to install.

**Comment by 0x3N3JVhPUV** [comment]
> 

As you can see on the following screenshot, I have a "besu-node-member-1" pod running in my cluster...
![image](https://user-images.githubusercontent.com/46408093/173231789-2dada0f4-bdba-4ed1-8df0-86a943bf50ed.png)

**Comment by anuj-upadhyay-inferenz** [comment]
Check the firewall settings for your cloud provider to ensure that either of ports `80,3000,4000,8545,9080` aren't being blocked.

Redeploying blockscout because it has already crashed quite a few times according to the output of the `kubectl get pods -n besu` command.

Also at last try applying this ingress provided:

[ingress-rules-besu.yml](https://github.com/anuj-upadhyay-inferenz/quorum-kubernetes/blob/blockscout-fix/ingress/ingress-rules-besu.yml) and try checking both the /blockscout and /blockscout-postgresql endpoints.

**Comment by 0x3N3JVhPUV** [comment]
Hello @anuj-upadhyay-inferenz,

The ports are not blocked, I redeployed blockscout, I update my ingress but nothing change...
However, the following link shows a solution to fix my issue, but I can't access the file where I'm supposed to make the changes.

https://github.com/blockscout/blockscout/pull/1572

Any Idea of how to do it?

Regerds,

**Comment by 0x3N3JVhPUV** [comment]
Hello @anuj-upadhyay-inferenz and @Ezzahhh,

I redeployed my cluster and followed your instructions and now, I get the following output, when I run ```kubectl logs blockscout-0 --namespace quorum```:

![image](https://user-images.githubusercontent.com/46408093/174075863-f7d96fb7-ddc4-4d3f-9cff-8b3e98990c0f.png)

I also don't have the confirmation that the node running the JSON-RPC service is syncing.
Indeed, here is the output of ```curl -v -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://<MY_INGRESS_IP>/rpc```:
![image](https://user-images.githubusercontent.com/46408093/174077305-1503f125-4409-4868-8eaf-50f867b3bd0a.png)

Here is the output of ```kubectl get pods --namespace quorum```:
![image](https://user-images.githubusercontent.com/46408093/174076139-cd85d7ff-69bd-448f-aa69-eaa05eb5bf25.png)

Here is my ingress-rules-besu.yml:
```
---
# ingress-nginx IngressClass
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: network-nginx
  namespace: quorum
spec:
  controller: k8s.io/network-ingress-nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: besu-ingress-routes
  namespace: quorum
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/tessera-[0-9]?/(.*) /$1 break;
      rewrite (?i)/tessera-[0-9]?$ / break;    
      rewrite (?i)/kibana/(.*) /$1 break;
      rewrite (?i)/kibana$ / break;
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/whitelist-source-range: w.x.y.z/32,a.b.c.d/32

spec:
  ingressClassName: network-nginx
  rules:
  - http:
      paths:
      - path: /rpc
        pathType: Prefix
        backend:
          service:
            name: besu-node-rpc-1
            port:
              number: 8545
      - path: /validator-1
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-1
            port:
              number: 8545
      - path: /validator-2
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-2
            port:
              number: 8545
      - path: /validator-3
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-3
            port:
              number: 8545
      - path: /validator-4
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-4
            port:
              number: 8545
      - path: /validator-5
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-5
            port:
              number: 8545
      - path: /validator-6
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-6
            port:
              number: 8545
      - path: /member-1
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-1
            port:
              number: 8545
      - path: /tessera-1
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-1
            port:
              number: 9080
      - path: /member-2
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-2
            port:
              number: 8545
      - path: /tessera-2
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-2
            port:
              number: 9080
      - path: /member-3
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-3
            port:
              number: 8545
      - path: /tessera-3
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-3
            port:
              number: 9080
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: kibana-kibana
            port:
              number: 5601
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 3000
      - path: /blockscout
        pathType: Prefix
        backend:
          service:
            name: blockscout
            port:
              number: 80
      - path: /blockscout-postgresql
        pathType: Prefix
        backend:
          service:
            name: blockscout-postgresql
            port:
              number: 80
```

Here is my charts/blockscout/values.yaml:
![image](https://user-images.githubusercontent.com/46408093/174077746-18c20134-b773-485d-96a0-d4dd9fa0f2e7.png)

I need help please.

Regerds

**Comment by Ezzahhh** [comment]
If you would like to have monitoring and rpc access, you will need to deploy two ingresses. I can see that you've deployed the monitoring ingress but you also need to deploy the other ingress. Please see the `quorum-network-ingress` https://github.com/ConsenSys/quorum-kubernetes/tree/master/helm#for-besu

**Comment by 0x3N3JVhPUV** [comment]
This is what I get when I'm trying to install ```quorum-network-ingress```:

![image](https://user-images.githubusercontent.com/46408093/174091392-9ac41abc-9c2a-426c-a1d5-7b2e0628088e.png)

To be honnest, I dont quite understand what I'm supposed to do here.

Can you shed some light for me? Please.

Regards,

**Comment by 0x3N3JVhPUV** [comment]
> @0x3N3JVhPUV You deployed the charts for the monitoring ingress but didn't apply ingress-rules-monitoring.yml
> 
> And you applied the ingress-rules-besu.yml file and didn't deploy the network ingress charts for it.
> 
> So you basically mismatched the values and the charts, that's why your rpc endpoint doesn't give a response as well.

Hello @anuj-upadhyay-inferenz ,

I actually deployed the charts for the monitoring ingress and apply ingress-rules-monitoring.yml
However, I indeed applied the ingress-rules-besu.yml file and didn't deploy the network ingress charts for it.
The reason why I couldn't deploy it's because of what follows:

This is what I get when I'm trying to install ```quorum-network-ingress```:
![image](https://user-images.githubusercontent.com/46408093/174091392-9ac41abc-9c2a-426c-a1d5-7b2e0628088e.png)

Based on this output, I replace ```--set controller.ingressClassResource.name="network-nginx" ``` by ``` --set controller.ingressClassResource.name="quorum-network-ingress"``` and I was able to install quorum-network-ingress.

However, I'm now getting a ````503 Service Temporarily Unavailable``` when running 
curl -v -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://<MY_INGRESS_IP>:80/rpc .

Here is the output:
![image](https://user-images.githubusercontent.com/46408093/174100416-30552539-e9a6-41ae-aef6-32a067161956.png)

Here is the output of kubectl get pods --namespace quorum:
![image](https://user-images.githubusercontent.com/46408093/174100669-b8b871fe-51bf-4afb-a2c6-cd2e79f839d6.png)

Any Idea on the origin of this 503 error?

Regards,

**Comment by Ezzahhh** [comment]
If you made that change to deploy then you need to modify this line: https://github.com/ConsenSys/quorum-kubernetes/blob/master/ingress/ingress-rules-besu.yml#L9

**Comment by anuj-upadhyay-inferenz** [comment]
@0x3N3JVhPUV I would recommend deploying the ingress-rules-besu.yml the same as the docs and just including a new endpoint for blockscout and blockscout-postgresql in the ingress-rules-monitoring.yml.

**Comment by 0x3N3JVhPUV** [comment]
Hello guys,

I have an internal error when running ```kubectl apply -f ../ingress/ingress-rules-monitoring.yml``` and I don't know why.
Here is the screenshot of the output:

![image](https://user-images.githubusercontent.com/46408093/174579484-1d85a3ed-2c62-4788-80e4-99bce0922dbd.png)

Do you know why I'm getting this Error message?

Regards,

**Comment by anuj-upadhyay-inferenz** [comment]
Hi @0x3N3JVhPUV 

1] The internal error you got was because you tried to apply the monitoring rules before the ingress service was actually up and running. If you see the output of your second command, it shows the service was only running for 12 secs and that was after you tried to apply the rules in the first place. If you try to apply the rules now, they will apply properly because the service is actually running now.

2] Grafana username is admin and password is prom-operator, password, admin. One of those 3 i don't remember exactly. It was prom-operator most likely.

3] You actually added the blockscout endpoints to your ingress-rules-besu file instead of ingress-rules-monitoring, i would just cut them from the former and paste into the latter and re-apply both rules and check the blockscout, blockscout-postgresql endpoints one more time.

**Comment by 0x3N3JVhPUV** [comment]
Thank you @anuj-upadhyay-inferenz,

Indeed, I just retried the command ```kubectl apply -f ../ingress/ingress-rules-monitoring.yml```.The error disappeared. I also cut and paste the blockscout endpoints to my ingress-rules-monitoring, re-apply both ingress rules and check the blockscout, blockscout-postgresql endpoints one more time and I'm getting a 404 error on the browser with ```http://<quorum-monitoring-ingress-ingress-nginx-controller external IP>/Blockscout```:

![image](https://user-images.githubusercontent.com/46408093/174595483-dbe5555b-1641-491b-812e-1ac3d09ee88d.png)

Did I miss something?

**Comment by 0x3N3JVhPUV** [comment]
> Ingress port number for Blockscout should be 4000 and not 80

I didn't have this information. It's working fine!

Thank you very much guys!

**Comment by 0x3N3JVhPUV** [comment]
Hello guys, 

I'm facing a new issue...
I redeploy my network with the same ingress config but Blocksckout return again a 503 error on the browser....
Here are some outputs: 
```kubectl logs blockscout-0 -n quorum```:
![image](https://user-images.githubusercontent.com/46408093/177020000-3e469ae6-3aed-4922-a49b-1bb5abb88361.png)

![image](https://user-images.githubusercontent.com/46408093/177020020-448b5096-9035-4e5d-9c25-6d0951a79b98.png)

![image](https://user-images.githubusercontent.com/46408093/177020177-46880041-ac54-4ef0-ad9d-96d3b92bb159.png)

Here is my ```ingress-rules-monitoring.yml``:
```
---
# ingress-nginx IngressClass
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: monitoring-nginx
  namespace: quorum
spec:
  controller: k8s.io/monitoring-ingress-nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: besu-ingress-monitoring-routes
  namespace: quorum
  annotations:
    nginx.ingress.kbernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/kibana/(.*) /$1 break;
      rewrite (?i)/kibana$ / break;
    #nginx.ingress.kubernetes.io/whitelist-source-range: w.x.y.z/32,a.b.c.d/32

spec:
  ingressClassName: monitoring-nginx
  rules:
  - http:
      paths:
      - path: /explorer
        pathType: Prefix
        backend:
          service:
            name: quorum-explorer
            port:
              number: 80
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: kibana-kibana
            port:
              number: 5601
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blockscout
            port:
              number: 4000
      - path: /blockscout-postgresql
        pathType: Prefix
        backend:
          service:
            name: blockscout-postgresql
            port:
              number: 4000
```
Why am I getting the following error: ```fetcher=block_realtime [error] GenServer Indexer.Block.Realtime.Fetcher terminating```?

Regards

**Comment by anuj-upadhyay-inferenz** [comment]
@0x3N3JVhPUV Have you tried redeploying it?

**Comment by 0x3N3JVhPUV** [comment]
> @0x3N3JVhPUV Have you tried redeploying it? and Have you made any changes to `blockscout-besu.yml`, more specifically to the line `ethereum_jsonrpc_transport: http`
> 
> Also you have `besu-node-bootnode-2` exposed on both `8545` and `8546`? Can you try removing the `8546` from your `ingress-rules-besu.yml`

Thank you for your answer @anuj-upadhyay-inferenz!

Yes I tried to redeploy it...

Here is my ```blockscout-besu.yml``` : 
```
---
image:
  blockscout:
    repository: consensys/blockscout
    tag: v4.0.0-beta
    pullPolicy: IfNotPresent

postgresql:
  postgresqlDatabase: postgres
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  initdbUser: postgres
  initdbPassword: postgres
  enabled: true

blockscout: # cpu dependent
  resources:
    cpuLimit: 0.7
    cpuRequest: 0.5
    memLimit: "2G"
    memRequest: "1G"
  port: 4000
  database_url: "ecto://postgres:postgres@blockscout-postgresql/postgres?ssl=false"
  postgres_password: postgres
  postgres_user: postgres
  network: quorum
  subnetwork: consensys
  chain_id: 1337
  coin: eth
  ethereum_jsonrpc_variant: besu
  ethereum_jsonrpc_transport: http
  ethereum_jsonrpc_endpoint: "besu-node-bootnode-2" # service name to be used
  secret_key_base: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # change me please
```

I didn't expose ```besu-node-bootnode-2``` on both 8545 and 8546 in my ingress-rules-besu.yml. Should I?
Here is my `ingress-rules-besu.yml`:
```
---
# ingress-nginx IngressClass
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: network-nginx
  namespace: quorum
spec:
  controller: k8s.io/network-ingress-nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: besu-ingress-routes
  namespace: quorum
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/tessera-[0-9]?/(.*) /$1 break;
      rewrite (?i)/tessera-[0-9]?$ / break;    
      rewrite (?i)/kibana/(.*) /$1 break;
      rewrite (?i)/kibana$ / break;
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/whitelist-source-range: w.x.y.z/32,a.b.c.d/32

spec:
  ingressClassName: network-nginx
  rules:
  - http:
      paths:
      - path: /rpc
        pathType: Prefix
        backend:
          service:
            name: besu-node-rpc-1
            port:
              number: 8545
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: besu-node-rpc-1
            port:
              number: 8546        
      - path: /validator-1
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-1
            port:
              number: 8545
      - path: /validator-2
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-2
            port:
              number: 8545
      - path: /validator-3
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-3
            port:
              number: 8545
      - path: /validator-4
        pathType: Prefix
        backend:
          service:
            name: besu-node-validator-4
            port:
              number: 8545
      - path: /member-1
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-1
            port:
              number: 8545
      - path: /tessera-1
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-1
            port:
              number: 9080
      - path: /member-2
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-2
            port:
              number: 8545
      - path: /tessera-2
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-2
            port:
              number: 9080
      - path: /member-3
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-3
            port:
              number: 8545
      - path: /tessera-3
        pathType: Prefix
        backend:
          service:
            name: besu-node-member-3
            port:
              number: 9080
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: kibana-kibana
            port:
              number: 5601
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 3000
```
Here's what I get when I'm trying to connect with the websocket:

![image](https://user-images.githubusercontent.com/46408093/177189155-7b66d6cb-aa36-43a9-9f27-0c35affee2da.png)

What can I do?
