### ISSUE TITLE
Blockscout is not showing transactions and new blocks.

### ISSUE THREAD

**Issue by 0x3N3JVhPUV** [ConsenSys/quorum-kubernetes#158]
Hello,

I successfully deployed Quorum-Kubernetes (azure).
Indeed, all the pods are running, blockscout and grafana are accessible on the browser and the HTTP RPC request returns the appropriate json.
However, for some reason blockscout is not showing transactions and new blocks.
Also, I can't connect to my private network through the websocket.

**CONFIGS:**
Here is my ```ingress-rules-monitoring.yml``:
```
---
# ingress-nginx IngressClass
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: monitoring-nginx
  namespace: quorum
spec:
  controller: k8s.io/monitoring-ingress-nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: besu-ingress-monitoring-routes
  namespace: quorum
  annotations:
    nginx.ingress.kbernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/kibana/(.*) /$1 break;
      rewrite (?i)/kibana$ / break;
    #nginx.ingress.kubernetes.io/whitelist-source-range: w.x.y.z/32,a.b.c.d/32

spec:
  ingressClassName: monitoring-nginx
  rules:
  - http:
      paths:
      - path: /explorer
        pathType: Prefix
        backend:
          service:
            name: quorum-explorer
            port:
              number: 80
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: kibana-kibana
            port:
              number: 5601
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blockscout
            port:
              number: 4000
      - path: /blockscout-postgresql
        pathType: Prefix
        backend:
          service:
            name: blockscout-postgresql
            port:
              number: 4000
```
Here is my blockscout-besu.yml :
```
---
image:
  blockscout:
    repository: consensys/blockscout
    tag: v4.0.0-beta
    pullPolicy: IfNotPresent

postgresql:
  postgresqlDatabase: postgres
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  initdbUser: postgres
  initdbPassword: postgres
  enabled: true

blockscout: # cpu dependent
  resources:
    cpuLimit: 0.7
    cpuRequest: 0.5
    memLimit: "2G"
    memRequest: "1G"
  port: 4000
  database_url: "ecto://postgres:postgres@blockscout-postgresql/postgres?ssl=false"
  postgres_password: postgres
  postgres_user: postgres
  network: quorum
  subnetwork: consensys
  chain_id: 1337
  coin: eth
  ethereum_jsonrpc_variant: besu
  ethereum_jsonrpc_transport: http
  ethereum_jsonrpc_endpoint: "besu-node-bootnode-2" # service name to be used
  secret_key_base: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # change me please
```

**OUPUTS**:
Here's what I get when I'm trying to connect with the websocket:
![image](https://user-images.githubusercontent.com/46408093/177810624-8b9a7be1-a4d0-4034-a676-757270d6736a.png)

```kubectl logs blockscout-0 -n quorum```:
![image](https://user-images.githubusercontent.com/46408093/177811809-22330ccb-ac29-47a8-a3d2-cfba468000ee.png)

```kubectl get pods -n quorum```:
![image](https://user-images.githubusercontent.com/46408093/177812088-63880bfc-d3da-45a6-b5b0-c9684cbadcd4.png)

![image](https://user-images.githubusercontent.com/46408093/177812317-c139be21-bdc4-4476-abf9-183150ab27ef.png)

**STEPS TO REPRODUCE:**
I'm deploying Quorum-Kubernetes(azure) with a custom script. 
Here are the steps to reproduce it:

1. In quorum-kubernetes/helm, create the script with the following command: ````nano myscript.sh ````
2. Add the following lines:  
```
#!/bin/bash

#Connect to your cluster
export RESOURCE_GROUP=xxxxxxxxxxxxx #your ressource groupe
printf "RESOURCE_GROUP=$RESOURCE_GROUP\n"
az account set --subscription xxxxxxxxxxxxxxxxx #Your subscriptionId
export CLUSTER_NAME=`az aks list --resource-group $RESOURCE_GROUP --query "[].name" --output tsv`
printf "CLUSTER_NAME=$CLUSTER_NAME\n"
az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME

#Saving identity ClientId in an environement variable:
export IDENTITY_CLIENTID=`az identity list --resource-group $RESOURCE_GROUP --query "[0].clientId" --output tsv`
printf "IDENTITY_CLIENTID=$IDENTITY_CLIENTID\n"
#Saving keyvault name in an environement variable:
export KEYVAULT_NAME=`az keyvault list --resource-group $RESOURCE_GROUP --query "[0].name" --output tsv`
printf "KEYVAULT_NAME=$KEYVAULT_NAME\n"

#Create a credential file:
cat << EOF  > ./credentials-Besu_cluster
RESOURCE_GROUP=$RESOURCE_GROUP
CLUSTER_NAME=$CLUSTER_NAME
IDENTITY_CLIENTID=$IDENTITY_CLIENTID
KEYVAULT_NAME=$KEYVAULT_NAME
EOF

#Installer envsubst:
curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
chmod +x envsubst

#Adapt your env variables accordingly:
./envsubst < charts/besu-genesis/values.yaml
./envsubst < values/genesis-besu.yml
./envsubst < charts/besu-node/values.yaml
./envsubst < values/bootnode.yml
./envsubst < values/reader.yml
./envsubst < values/txnode.yml
./envsubst < values/validator.yml

#Enable AAD pod identities which use the managed identity
az feature register --name EnablePodIdentityPreview --namespace Microsoft.ContainerService
az feature list --namespace Microsoft.ContainerService -o table
az extension add --name aks-preview
az extension update --name aks-preview

#Run the bootstrap to provision the AAD pod identity and the CSI drivers
cd ../azure
# export RESSOURCE_GROUP=besuTestNet
printf "CLUSTER_NAME=$CLUSTER_NAME\n"
# export CLUSTER_NAME=`az aks list --resource-group besuTestNet --query "[].name" --output tsv`
printf "RESOURCE_GROUP=$RESOURCE_GROUP\n"
export DNS_PREFIX=`az aks list --resource-group besuTestNet --query "[].dnsPrefix" --output tsv`
printf "DNS_PREFIX=$DNS_PREFIX\n"
./scripts/bootstrap.sh "$RESOURCE_GROUP" "$CLUSTER_NAME" "$DNS_PREFIX-ops-identity" "quorum"
cd ../helm

#uninstall pods
helm uninstall monitoring --namespace quorum
helm uninstall genesis --namespace quorum
helm uninstall bootnode-1 bootnode-2 --namespace quorum
helm uninstall validator-1 validator-2 validator-3 validator-4 --namespace quorum
helm uninstall rpc-1 -n quorum
helm uninstall member-1 -n quorum
helm uninstall blockscout --namespace quorum
helm uninstall quorum-monitoring-ingress --namespace quorum
helm uninstall quorum-network-ingress --namespace quorum
helm uninstall quorum-explorer --namespace quorum
sleep 20

#install monitoring
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install monitoring prometheus-community/kube-prometheus-stack --version 34.10.0 --namespace=quorum --create-namespace --values ./values/monitoring.yml --wait
kubectl --namespace quorum apply -f  ./values/monitoring/


#install quorum-monitoring-ingress
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
helm install quorum-monitoring-ingress ingress-nginx/ingress-nginx \
    --namespace quorum \
    --set controller.ingressClassResource.name="quorum-network-ingress" \
    --set controller.ingressClassResource.controllerValue="k8s.io/monitoring-ingress-nginx" \
    --set controller.replicaCount=1 \
    --set controller.nodeSelector."kubernetes\.io/os"=linux \
    --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.admissionWebhooks.patch.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.service.externalTrafficPolicy=Local

sleep 60
kubectl apply -f ../ingress/ingress-rules-monitoring.yml
kubectl -n quorum get services quorum-monitoring-ingress-ingress-nginx-controller

#install genesis
helm install genesis ./charts/besu-genesis --namespace quorum --create-namespace --values ./values/genesis-besu.yml
sleep 60 

# bootnodes - optional but recommended
helm install bootnode-1 ./charts/besu-node --namespace quorum --values ./values/bootnode.yml
sleep 60

helm install bootnode-2 ./charts/besu-node --namespace quorum --values ./values/bootnode.yml
sleep 60
# !! IMPORTANT !! - If you use bootnodes, please set `quorumFlags.usesBootnodes: true` in the override yaml files
# for validator.yml, txnode.yml, reader.yml

#install genesis validators   
helm install validator-1 ./charts/besu-node --namespace quorum --values ./values/validator.yml
helm install validator-2 ./charts/besu-node --namespace quorum --values ./values/validator.yml
helm install validator-3 ./charts/besu-node --namespace quorum --values ./values/validator.yml
helm install validator-4 ./charts/besu-node --namespace quorum --values ./values/validator.yml
sleep 120

# spin up a besu and tessera node pair
helm install member-1 ./charts/besu-node --namespace quorum --values ./values/txnode.yml
sleep 100

# spin up a besu rpc node
helm install rpc-1 ./charts/besu-node --namespace quorum --values ./values/reader.yml
sleep 100

#Explorer: Blockscout
helm dependency update ./charts/blockscout
helm install blockscout ./charts/blockscout --namespace quorum --values ./values/blockscout-besu.yml
sleep 120
#Explorer: quorum-explorer
# helm install quorum-explorer ./charts/explorer --namespace quorum --create-namespace --values ./values/explorer-besu.yaml
# watch kubectl get pods --namespace quorum


# Install Ingress
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
helm install quorum-network-ingress ingress-nginx/ingress-nginx \
    --namespace quorum \
    --set controller.ingressClassResource.name="quorum-monitoring-ingress" \
    --set controller.ingressClassResource.controllerValue="k8s.io/network-ingress-nginx" \
    --set controller.replicaCount=1 \
    --set controller.nodeSelector."kubernetes\.io/os"=linux \
    --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.admissionWebhooks.patch.nodeSelector."kubernetes\.io/os"=linux \
    --set controller.service.externalTrafficPolicy=Local

sleep 60
# Apply ingress config
kubectl apply -f ../ingress/ingress-rules-besu.yml

```

3. Add your resource groupe name and your subscriptionId in the script.
4. Change rights with the following command: ```chmod +x  myscript.sh```
5. Make sure to replace the value of identityClientId and keyvaultName by ${IDENTITY_CLIENTID} and ${KEYVAULT_NAME} in:
charts/besu-genesis/values.yaml
values/genesis-besu.yml
charts/besu-node/values.yaml
values/bootnode.yml
values/reader.yml
values/txnode.yml
values/validator.yml
6. Run th script with: ```./myscript.sh ```

**2 questions:**
**Why ```kubectl logs blockscout-0 -n quorum``` returns such an error?
Why I'm gettting a 502 error when I'm trying reach my private network with the websoscket?**
