### ISSUE TITLE
How to update the genesis without shuting down my cluster?

### ISSUE THREAD

**Issue by 0x3N3JVhPUV** [ConsenSys/quorum-kubernetes#159]
Hello,

I'd like to update the genesis without shuting down my cluster.
Here is my genesis:
```
rawGenesisConfig:
  genesis:
    config:
      berlinblock: 0
      chainId: 1337
      ibft2:
        blockperiodseconds: 5
        epochlength: 30000
        requesttimeoutseconds: 10
    nonce: '0x0'
    timestamp: '0x58ee40ba'
    gasLimit: '0x3B9ACA00'
    difficulty: '0x1'
    mixHash: '0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365'
    coinbase: '0x0000000000000000000000000000000000000000'
    alloc:
      f90acf91bdab539aac3093e5c5b207b562354401:
        balance: '0x446c3b15f9926687d2c40534fdb564000000000000'
  blockchain:
    nodes:
      generate: true
      count: 6
```
Here is how I'd like to change it:
```
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      algorithm:
        consensus: ibft2
        blockperiodseconds: 10
        epochlength: 30000
        requesttimeoutseconds: 20
    nonce: '0x0'   
    gasLimit: '0xf7b760'
    difficulty: '0x1'
    coinbase: '0x0000000000000000000000000000000000000000'
    alloc:
      f90acf91bdab539aac3093e5c5b207b562354401:
        balance: '0x446c3b15f9926687d2c40534fdb564000000000000'
  blockchain:
    nodes:
      generate: true
      count: 4
    accountPassword: 'password'
```
According to the Besu documentation, it's recommended to use the transitions genesis configuration item in order to specify a future block number at which to change IBFT 2.0 network configuration in an existing network.
Thus, I configured my genesis like that:
```
rawGenesisConfig:
  genesis:
    config:
      berlinblock: 0
      chainId: 1337
      ibft2:
        blockperiodseconds: 5
        epochlength: 30000
        requesttimeoutseconds: 10
      transitions:
        ibft2:
          block: <FutureBlockNumber>,
          blockperiodseconds: <NewValue>
          requesttimeoutseconds: <NewValue>
    nonce: '0x0'
    timestamp: '0x58ee40ba'
    gasLimit: '0x3B9ACA00'
    difficulty: '0x1'
    mixHash: '0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365'
    coinbase: '0x0000000000000000000000000000000000000000'
    alloc:
      f90acf91bdab539aac3093e5c5b207b562354401:
        balance: '0x446c3b15f9926687d2c40534fdb564000000000000'
  blockchain:
    nodes:
      generate: true
      count: 6
```
However, I'd also like to update and add others values such as the gasLimit or the timestamp but I dont know how.

Can you help me please?

Regards,
