### ISSUE TITLE
"authenticationEnabled: true" Doesn't work

### ISSUE THREAD

**Issue by 0x3N3JVhPUV** [ConsenSys/quorum-kubernetes#188]
Hello,

In "helm/chart/besu-node/values.yaml", I changed the value of "authenticationEnabled" to "true". However, my pod is in "crashloop" state after updating.
So, I managed to create a volume hosting the .toml file containing the credentials for the authentication of the user wishing to go through my services to access the besu methods.
I tested with validator-3. but it still crashloops with the following output:
````
Defaulted container "validator-3-besu" out of: validator-3-besu, volume-permission-besu (init)
Invalid TOML configuration: org.apache.tuweni.toml.TomlParseError: Unexpected '/', expected ', ", ''', """, a number, a boolean, a date/time, an array, or a table (line 38, column 42)

To display full help:
besu [COMMAND] --help
2023-02-14 14:42:34.695+00:00 | main | INFO  | Besu | Using jemalloc
````
I don't know where this error is coming from. Can you help me on that one? 

Here are my configs:

**helm/chart/besu-node/values.yaml:**
```
rpc:
      enabled: true
      host: "0.0.0.0"
      port: 8545
      api: '["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "TRACE", "EEA", "PRIV", "QBFT", "PERM", "TXPOOL"]'
      corsOrigins: '["all"]'
      authenticationEnabled: true
      authPath: "/config/auth/auth_config.toml"
```

**helm/chart/besu-node/template/besu-config-configmap.yaml:**
````
{{ if  .Values.node.besu.rpc.enabled -}}
    # JSON-RPC
    rpc-http-enabled={{ .Values.node.besu.rpc.enabled }}
    rpc-http-host={{ .Values.node.besu.rpc.host | quote }}
    rpc-http-port={{ .Values.node.besu.rpc.port }}
    rpc-http-api={{ .Values.node.besu.rpc.api }}
    rpc-http-cors-origins={{ .Values.node.besu.rpc.corsOrigins }}
    rpc-http-authentication-enabled={{ .Values.node.besu.rpc.authenticationEnabled }}
    rpc-http-authentication-credentials-file={{ .Values.node.besu.rpc.authPath }}
    revert-reason-enabled=true
    {{ end }}
````

**charts/besu-node/templates/node-statefulset.yaml**
````
          - name: genesis
            mountPath: /etc/genesis
            readOnly: true
          - name: static-nodes
            mountPath: /config/static
          - name: besu-config
            mountPath: /etc/besu
            readOnly: true
          - name: auth-config
            mountPath: /config/auth
          - name: data
            mountPath: {{ .Values.node.besu.dataPath }}
````
````
{{- if .Values.node.besu.rpc.authenticationEnabled }}
      - name: auth-config
        configMap:
          name: {{ include "besu-node.fullname" . }}-auth
{{- end }}
````

**charts/besu-node/templates/auth-configmap.yaml**
````
{{- if .Values.node.besu.rpc.authenticationEnabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "besu-node.fullname" . }}-auth
  labels:
    app.kubernetes.io/name: {{ include "besu-node.name" . }}
    helm.sh/chart: {{ include "besu-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  auth_config.toml: |-
    # auth TOML file
    [Users.username1]
    password = "************************************"
    permissions=["*:*"]
{{- end -}}
````

Regards,

**Comment by anuj-upadhyay-inferenz** [comment]
In your auth_config.toml, you need to put the array values in single quotes, e.g
`permissions='["*:*"]'`

**Comment by anuj-upadhyay-inferenz** [comment]
Replace following config:
 **charts/besu-node/templates/auth-configmap.yaml**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "besu-node.fullname" . }}-auth
  labels:
    app.kubernetes.io/name: {{ include "besu-node.name" . }}
    helm.sh/chart: {{ include "besu-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  auth_config.toml: |-
    {{ if .Values.node.besu.rpc.authenticationEnabled -}}
    # auth TOML file
    [Users.username1]
    password ={{ .Values.node.besu.rpc.password }}
    permissions={{ .Values.node.besu.rpc.permissions }}
    {{- end -}}
```

**Comment by 0x3N3JVhPUV** [comment]
Hello @anuj-upadhyay-inferenz,

Thank you for your quick answer!

I applied the change but it still didn't change anything.
I still have a crashloop and the following output:
````
Defaulted container "validator-3-besu" out of: validator-3-besu, volume-permission-besu (init)
Invalid TOML configuration: org.apache.tuweni.toml.TomlParseError: Unexpected '/', expected ', ", ''', """, a number, a boolean, a date/time, an array, or a table (line 38, column 42)

To display full help:
besu [COMMAND] --help
2023-02-14 14:42:34.695+00:00 | main | INFO  | Besu | Using jemalloc
````
How did you know that line 38 of config.toml would be around line 54 of besu-config-configmap.yaml?
Where does this "Unexpected '/'" is coming from?

**Comment by anuj-upadhyay-inferenz** [comment]
@0x3N3JVhPUV The "Unexpected '/'" error occurs if there is invalid syntax in a TOML file. But the issue with TOML is that it doesn't tell you which file it is in, it just tells you the line number.

And since we are only changing two files **auth_config.toml** and **config.toml**, the error can only be in one of those files, but the size of **auth_config.toml** is 6 lines, so the only file where the error could be is the **config.toml** which is mounted in the data for the **besu-config-configmap.yaml**.

**Comment by 0x3N3JVhPUV** [comment]
In my **config.toml**, line 54 begin by this:
```
    p2p: <------ line 54
      enabled: true
      host: "0.0.0.0"
      port: 30303
      discovery: false
      staticNodes: "/config/static/static-nodes.json"
      maxPeers: 25
    rpc:
      enabled: true
      host: "0.0.0.0"
      port: 8545
      api: '["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "TRACE", "EEA", "PRIV", "QBFT", "PERM", "TXPOOL"]'
      corsOrigins: '["all"]'
      authenticationEnabled: true <------ line 68
      authPath: "/config/auth/auth_config.toml" <------ line 69
      password: "*****************************************" <------ line 70
      permissions: '["*:*"]'
```
Thus, if there is an invalid syntax, it would be on line 68, 69 or 70.
However, I don't see any invalid syntax on those lines.
So what's is wrong with line 68, 69 or 70?
